=== ernscht/generator-nitro/packages/project-nitro/src/patterns/test/Ex/schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "/test/Ex",
	"title": "Ex",
	"description": "An Ex organism",
	"type": "object",
	"properties": {
		"modifier": {
			"description": "A modifier",
			"enum": ["", "blue"]
		},
		"title": {
			"description": "Title of the pattern",
			"type": "string",
			"minLength": 3,
			"maxLength": 100
		},
		"links": {
			"description": "An array of links",
			"type": "array",
			"minItems": 1,
			"items": {
				"$ref": "/test/Ex/Ex-link"
			}
		},
		"buttons": {
			"description": "a boolean",
			"type": "boolean"
		},
		"subpattern": {
			"$ref": "/test/t"
		}
	},
	"required": ["title", "links"]
}

=== ernscht/generator-nitro/packages/project-nitro/src/patterns/test/Ex/_data/ex-subpattern.json
{
	"$schema": "../schema.json",
	"modifier": "blue",
	"title": "Ex Module with Skin Blue (data: ex-blue.json)",
	"links": [
		{
			"uri": "index",
			"text": "Ex One"
		},
		{
			"uri": "index",
			"text": "Ex Two"
		},
		{
			"uri": "index",
			"text": "Ex Three"
		}
	],
	"subpattern": {
		"modifier": "",
		"linkText": "Go to (subpattern): ",
		"dynInsert": {
			"you": "developer (subpattern)"
		},
		"dynChildren": {
			"count": 1
		},
		"first": "first",
		"one": "a",
		"two": "b",
		"three": "c",
		"four": "d",

		"content": "content string (subpattern)",
		"linkText": "linkText (subpattern)",
		"test": {
			"text": "test.text (subpattern)",
			"test": "test.test (subpattern)"
		}
	}
}
